### PR TITLE
Relative Links

### PR DESCRIPTION
**Pull request by escowles**
* Convert all links and asset references to relative links
* Move assets to `assets` directory
* Remove copies of content
* Add script to copy all assets and perform XSLT with output in the `dist` directory

### CODE REVIEW

**Comment by escowles** [comment]
Closing this PR — this functionality has been replaced by OARSC, so this improvement is not needed.

**Comment by escowles** [comment]
This use case has resurfaced, and OARSC does not satisfy the need, so I'm re-opening this PR.

**Comment by regineheberlein** [comment]
The display looks good now with ASpace exports when testing locally, except the PDFs since I don't have them on my machine. I left a note in the README on how to test.

**Review by sdellis — APPROVED** [review]
I can't test this locally, but the code changes look good to me! 👍

**Comment by escowles** [comment]
One of the Figgy parts of this process has been removed (the part that updated the DAOs to point to local PDFs instead of at Figgy). But I think we should merge this and fix that separately.

**Comment by escowles** [comment]
One of the Figgy parts of this process has been removed (the part that updated the DAOs to point to local PDFs instead of at Figgy). But I think we should merge this and fix that separately.

**Comment by regineheberlein** [comment]
In which file would that have happened? (I'm pretty sure I didn't touch dao...)

**Comment by escowles** [comment]
@regineheberlein Sorry, I mean removed from Figgy — there was one Rake task to export PDFs and a second one to update the EAD XML to point to the PDFs instead of to HTTP URLs (this second task was removed). I think we can probably just update `spv.xsl` to do this part instead of restoring the Figgy code which is pretty complex because it's related to the old code to add the DAOs pointing to Figgy in the first place).

**Comment by regineheberlein** [comment]
Ah, removed from Figgy! Ok. You had me worried there for a sec!

**Comment by regineheberlein** [comment]
Looks like it would be this template--what does it need to do differently?
```
<xsl:template match="ead:dao | ead:did/ead:dao">
		<a>
			<xsl:attribute name="href">
				<xsl:value-of select="@xlink:href"/>
			</xsl:attribute>
			<xsl:attribute name="class">
				<xsl:text>btn small</xsl:text>
			</xsl:attribute>
			<xsl:attribute name="target">
				<xsl:text>_blank</xsl:text>
			</xsl:attribute> View PDF </a>
	</xsl:template>
```

**Comment by escowles** [comment]
Instead of the Figgy URL from `@xlink:href`, it should link to the PDF files on disk, which are named after the component IDs (e.g., `pdf/c3.pdf`)

**Comment by regineheberlein** [comment]
Ok, I'll add that.

Interestingly, it looks like C1491 already has dao's that do that, but they're in addition to figgy-style ones. Whereas C0686 only has the figgy-style ones.

```
<dao xlink:actuate="onRequest" xlink:href="pdf/c105.pdf"
										xlink:show="new" xlink:title="View digital content"
										xlink:type="simple">
										<daodesc>
											<p>View digital content</p>
										</daodesc>
									</dao>
									<dao xlink:actuate="onRequest"
										xlink:href="https://figgy.princeton.edu/concern/scanned_resources/b92c322b-b8e4-48f9-9039-bbee6500d118/manifest"
										xlink:role="https://iiif.io/api/presentation/2.1/"
										xlink:show="new" xlink:title="View digital content"
										xlink:type="simple">
										<daodesc>
											<p>View digital content</p>
										</daodesc>
									</dao>
```

**Comment by escowles** [comment]
Oh, I bet those DAOs linking to `pdf/c105.pdf` were accidentally added and should probably be removed. The old process updated the files on disk and then reverted the changes after the export — if that went wrong, I can imagine the separate process that added the DAO links to Figgy committing those by mistake.

**Comment by regineheberlein** [comment]
I'll give Will Clements a heads-up about removing those dao's before I actually do it.

**Pull request merged**
